library(reticulate); library(imager)
library(IRdisplay); library(ggplot2)
pl<-c('matplotlib','pandas','sklearn',
      'seaborn','h5py','scikit-image')
for (p in pl) {py_install(p)} 
np<-import('numpy'); pd<-import('pandas')
sl<-import('sklearn'); sm<-import('skimage')
ks<-import('keras'); h5<-import('h5py')
pl<-import('pylab'); sn<-import('seaborn')
slds<-import('sklearn.datasets')
slpp<-import('sklearn.preprocessing')
slim<-import('sklearn.impute')
slfe<-import('sklearn.feature_extraction')
slms<-import('sklearn.model_selection')
slme<-import('sklearn.metrics')
sllm<-import('sklearn.linear_model')
slen<-import('sklearn.ensemble')
slne<-import('sklearn.neighbors')
slcl<-import('sklearn.cluster')