
reg1<-slen$GradientBoostingRegressor()
reg1$fit(X_train1,y_train1)    
y_reg_train11<-reg1$predict(X_train1)
y_reg_test11<-reg1$predict(X_test1)        
r2_reg_train11<-slme$r2_score(y_train1,y_reg_train11)
r2_reg_test11<-slme$r2_score(y_test1,y_reg_test11)
print('Gradient Boosting =>>>')
print(c(r2_reg_train11,r2_reg_test11))
reg2<-slne$KNeighborsRegressor()
reg2$fit(X_train1,y_train1)    
y_reg_train12<-reg2$predict(X_train1)
y_reg_test12<-reg2$predict(X_test1)        
r2_reg_train12<-slme$r2_score(y_train1,y_reg_train12)
r2_reg_test12<-slme$r2_score(y_test1,y_reg_test12)
print('KNeighbors =>>>')
print(c(r2_reg_train12,r2_reg_test12))
pl$figure(figsize=c(10,5)); k<-30
pl$scatter(1:k,y_test1[1:k],marker='*',s=100,
           color='black',label='Real data')
pl$plot(1:k,y_reg_test11[1:k],lw=2,label='Gradient Boosting')
pl$plot(1:k,y_reg_test12[1:k],lw=2,label='KNeighbors')
pl$xlabel('Observations'); pl$ylabel('Targets')
pl$title('Regressors. Test Results. Boston')
pl$legend(loc=2,fontsize=10); pl$tight_layout()
pl$savefig('rpy_p1.png'); im<-load.image('rpy_p1.png')
options(repr.plot.width=10,repr.plot.height=5)
par(mar=c(0,0,0,0)); plot(im,axes=FALSE)

